services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ahihi-mssql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"Password123\" -Q \"SELECT 1\" || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always

volumes:
  mssql_data:
